name: Lint files
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  lint-web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run lint script
        run: pnpm lint
  lint-rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './src-tauri'
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Install Tauri prerequisites
        run: sudo apt install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
      - name: Check format
        run: rustfmt --check
      - name: Cargo Check
        run: cargo check
